package com.ruipeng.dao.mapper;

import com.ruipeng.pojo.AuthorityTa;
import com.ruipeng.pojo.AuthorityTaExample;
import org.apache.ibatis.annotations.Param;


import java.util.List;

public interface AuthorityTaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTHORITY_TA
     *
     * @mbggenerated Fri May 11 22:18:35 CST 2018
     */
    int countByExample(AuthorityTaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTHORITY_TA
     *
     * @mbggenerated Fri May 11 22:18:35 CST 2018
     */
    int deleteByExample(AuthorityTaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTHORITY_TA
     *
     * @mbggenerated Fri May 11 22:18:35 CST 2018
     */
    int deleteByPrimaryKey(String userauthority);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTHORITY_TA
     *
     * @mbggenerated Fri May 11 22:18:35 CST 2018
     */
    int insert(AuthorityTa record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTHORITY_TA
     *
     * @mbggenerated Fri May 11 22:18:35 CST 2018
     */
    int insertSelective(AuthorityTa record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTHORITY_TA
     *
     * @mbggenerated Fri May 11 22:18:35 CST 2018
     */
    List<AuthorityTa> selectByExample(AuthorityTaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTHORITY_TA
     *
     * @mbggenerated Fri May 11 22:18:35 CST 2018
     */
    AuthorityTa selectByPrimaryKey(String userauthority);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTHORITY_TA
     *
     * @mbggenerated Fri May 11 22:18:35 CST 2018
     */
    int updateByExampleSelective(@Param("record") AuthorityTa record, @Param("example") AuthorityTaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTHORITY_TA
     *
     * @mbggenerated Fri May 11 22:18:35 CST 2018
     */
    int updateByExample(@Param("record") AuthorityTa record, @Param("example") AuthorityTaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTHORITY_TA
     *
     * @mbggenerated Fri May 11 22:18:35 CST 2018
     */
    int updateByPrimaryKeySelective(AuthorityTa record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AUTHORITY_TA
     *
     * @mbggenerated Fri May 11 22:18:35 CST 2018
     */
    int updateByPrimaryKey(AuthorityTa record);
}