package com.ruipeng.dao.mapper;

import com.ruipeng.pojo.UserTa;
import com.ruipeng.pojo.UserTaExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;


public interface UserTaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_TA
     *
     * @mbggenerated Fri May 11 22:16:56 CST 2018
     */
    int countByExample(UserTaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_TA
     *
     * @mbggenerated Fri May 11 22:16:56 CST 2018
     */
    int deleteByExample(UserTaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_TA
     *
     * @mbggenerated Fri May 11 22:16:56 CST 2018
     */
    int deleteByPrimaryKey(String useraccount);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_TA
     *
     * @mbggenerated Fri May 11 22:16:56 CST 2018
     */
    int insert(UserTa record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_TA
     *
     * @mbggenerated Fri May 11 22:16:56 CST 2018
     */
    int insertSelective(UserTa record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_TA
     *
     * @mbggenerated Fri May 11 22:16:56 CST 2018
     */
    List<UserTa> selectByExample(UserTaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_TA
     *
     * @mbggenerated Fri May 11 22:16:56 CST 2018
     */
    UserTa selectByPrimaryKey(String useraccount);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_TA
     *
     * @mbggenerated Fri May 11 22:16:56 CST 2018
     */
    int updateByExampleSelective(@Param("record") UserTa record, @Param("example") UserTaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_TA
     *
     * @mbggenerated Fri May 11 22:16:56 CST 2018
     */
    int updateByExample(@Param("record") UserTa record, @Param("example") UserTaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_TA
     *
     * @mbggenerated Fri May 11 22:16:56 CST 2018
     */
    int updateByPrimaryKeySelective(UserTa record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_TA
     *
     * @mbggenerated Fri May 11 22:16:56 CST 2018
     */
    int updateByPrimaryKey(UserTa record);
}