package com.ruipeng.pojo;

public class AuthorityTa {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AUTHORITY_TA.userAuthority
     *
     * @mbggenerated Fri May 11 22:18:35 CST 2018
     */
    private String userauthority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AUTHORITY_TA.listLevel
     *
     * @mbggenerated Fri May 11 22:18:35 CST 2018
     */
    private String listlevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AUTHORITY_TA.listPostfix
     *
     * @mbggenerated Fri May 11 22:18:35 CST 2018
     */
    private String listpostfix;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AUTHORITY_TA.academy
     *
     * @mbggenerated Fri May 11 22:18:35 CST 2018
     */
    private String academy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AUTHORITY_TA.userAuthority
     *
     * @return the value of AUTHORITY_TA.userAuthority
     *
     * @mbggenerated Fri May 11 22:18:35 CST 2018
     */
    public String getUserauthority() {
        return userauthority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AUTHORITY_TA.userAuthority
     *
     * @param userauthority the value for AUTHORITY_TA.userAuthority
     *
     * @mbggenerated Fri May 11 22:18:35 CST 2018
     */
    public void setUserauthority(String userauthority) {
        this.userauthority = userauthority == null ? null : userauthority.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AUTHORITY_TA.listLevel
     *
     * @return the value of AUTHORITY_TA.listLevel
     *
     * @mbggenerated Fri May 11 22:18:35 CST 2018
     */
    public String getListlevel() {
        return listlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AUTHORITY_TA.listLevel
     *
     * @param listlevel the value for AUTHORITY_TA.listLevel
     *
     * @mbggenerated Fri May 11 22:18:35 CST 2018
     */
    public void setListlevel(String listlevel) {
        this.listlevel = listlevel == null ? null : listlevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AUTHORITY_TA.listPostfix
     *
     * @return the value of AUTHORITY_TA.listPostfix
     *
     * @mbggenerated Fri May 11 22:18:35 CST 2018
     */
    public String getListpostfix() {
        return listpostfix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AUTHORITY_TA.listPostfix
     *
     * @param listpostfix the value for AUTHORITY_TA.listPostfix
     *
     * @mbggenerated Fri May 11 22:18:35 CST 2018
     */
    public void setListpostfix(String listpostfix) {
        this.listpostfix = listpostfix == null ? null : listpostfix.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AUTHORITY_TA.academy
     *
     * @return the value of AUTHORITY_TA.academy
     *
     * @mbggenerated Fri May 11 22:18:35 CST 2018
     */
    public String getAcademy() {
        return academy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AUTHORITY_TA.academy
     *
     * @param academy the value for AUTHORITY_TA.academy
     *
     * @mbggenerated Fri May 11 22:18:35 CST 2018
     */
    public void setAcademy(String academy) {
        this.academy = academy == null ? null : academy.trim();
    }
}