package com.ruipeng.pojo;

public class UserTa {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_TA.userAccount
     *
     * @mbggenerated Fri May 11 22:16:56 CST 2018
     */
    private String useraccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_TA.userPassword
     *
     * @mbggenerated Fri May 11 22:16:56 CST 2018
     */
    private String userpassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_TA.userName
     *
     * @mbggenerated Fri May 11 22:16:56 CST 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_TA.userPhoneNumber
     *
     * @mbggenerated Fri May 11 22:16:56 CST 2018
     */
    private String userphonenumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_TA.userEmail
     *
     * @mbggenerated Fri May 11 22:16:56 CST 2018
     */
    private String useremail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_TA.userAuthority
     *
     * @mbggenerated Fri May 11 22:16:56 CST 2018
     */
    private String userauthority;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_TA.userAccount
     *
     * @return the value of USER_TA.userAccount
     *
     * @mbggenerated Fri May 11 22:16:56 CST 2018
     */
    public String getUseraccount() {
        return useraccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_TA.userAccount
     *
     * @param useraccount the value for USER_TA.userAccount
     *
     * @mbggenerated Fri May 11 22:16:56 CST 2018
     */
    public void setUseraccount(String useraccount) {
        this.useraccount = useraccount == null ? null : useraccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_TA.userPassword
     *
     * @return the value of USER_TA.userPassword
     *
     * @mbggenerated Fri May 11 22:16:56 CST 2018
     */
    public String getUserpassword() {
        return userpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_TA.userPassword
     *
     * @param userpassword the value for USER_TA.userPassword
     *
     * @mbggenerated Fri May 11 22:16:56 CST 2018
     */
    public void setUserpassword(String userpassword) {
        this.userpassword = userpassword == null ? null : userpassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_TA.userName
     *
     * @return the value of USER_TA.userName
     *
     * @mbggenerated Fri May 11 22:16:56 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_TA.userName
     *
     * @param username the value for USER_TA.userName
     *
     * @mbggenerated Fri May 11 22:16:56 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_TA.userPhoneNumber
     *
     * @return the value of USER_TA.userPhoneNumber
     *
     * @mbggenerated Fri May 11 22:16:56 CST 2018
     */
    public String getUserphonenumber() {
        return userphonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_TA.userPhoneNumber
     *
     * @param userphonenumber the value for USER_TA.userPhoneNumber
     *
     * @mbggenerated Fri May 11 22:16:56 CST 2018
     */
    public void setUserphonenumber(String userphonenumber) {
        this.userphonenumber = userphonenumber == null ? null : userphonenumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_TA.userEmail
     *
     * @return the value of USER_TA.userEmail
     *
     * @mbggenerated Fri May 11 22:16:56 CST 2018
     */
    public String getUseremail() {
        return useremail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_TA.userEmail
     *
     * @param useremail the value for USER_TA.userEmail
     *
     * @mbggenerated Fri May 11 22:16:56 CST 2018
     */
    public void setUseremail(String useremail) {
        this.useremail = useremail == null ? null : useremail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_TA.userAuthority
     *
     * @return the value of USER_TA.userAuthority
     *
     * @mbggenerated Fri May 11 22:16:56 CST 2018
     */
    public String getUserauthority() {
        return userauthority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_TA.userAuthority
     *
     * @param userauthority the value for USER_TA.userAuthority
     *
     * @mbggenerated Fri May 11 22:16:56 CST 2018
     */
    public void setUserauthority(String userauthority) {
        this.userauthority = userauthority == null ? null : userauthority.trim();
    }
}